# LambdaTest Configuration

# Project configuration
project_id: "01KMMN2BBB2CPZWDFYX5KME5R0"

# Test Run configuration
assignee: 851912
environment_id: 62298

# Test URL for automation
test_url: "https://demo.lambdatestinternal.com"
